version: "3.0"

services: 
  frontend:
    container_name: ttkfront
    build:
      context: .  # ← путь до твоей React-папки
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # CRA использует порт 3000
    volumes:
      - /app/node_modules
    networks:
      - custom
    environment:
      - CHOKIDAR_USEPOLLING=true  # помогает hot-reload в Docker
    command: npm start  # ← запуск обычного CRA

networks:
  custom:
    driver: bridge
