"""migrations2

Revision ID: 00c1dcdb2030
Revises: 51de4e7c7b23
Create Date: 2025-04-05 04:51:18.780671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00c1dcdb2030'
down_revision = '51de4e7c7b23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_names', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('tasks', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'image_names')
    # ### end Alembic commands ###
