"""migrations1

Revision ID: 403bec1600fa
Revises: 
Create Date: 2025-04-06 08:27:52.726207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '403bec1600fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(), nullable=False),
    sa.Column('user_login', sa.String(), nullable=False),
    sa.Column('change_event', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id_article', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_article'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id_article')
    )
    op.create_table('task_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('task_title', sa.String(), nullable=False),
    sa.Column('user_login', sa.String(), nullable=False),
    sa.Column('change_event', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id_task', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assignee_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('assignee_login', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_task'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id_task')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('task_history')
    op.drop_table('articles')
    op.drop_table('article_history')
    # ### end Alembic commands ###
