"""migrations1

Revision ID: 51de4e7c7b23
Revises: 75e66edc80cf
Create Date: 2025-04-05 04:05:57.173262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51de4e7c7b23'
down_revision = '75e66edc80cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tasks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
